# Generated by Django 5.2 on 2026-05-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(default='onsite', max_length=50),
        ),
    ]
