# Generated by Django 5.2 on 2026-05-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_job_work_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.CharField(default='Any', max_length=100),
        ),
    ]
