# Generated by Django 5.2 on 2026-05-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_job_qualification'),
        ('Student', '0007_appliedjobs_assessment_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('assess_type', models.CharField(choices=[('mcq', 'MCQ'), ('coding', 'Coding Challenge'), ('file', 'File Upload')], default='mcq', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='Student.appliedjobs')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('mode', models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Call'), ('in-person', 'In-Person')], default='video', max_length=20)),
                ('meeting_link', models.CharField(blank=True, max_length=500)),
                ('interviewer_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='Student.appliedjobs')),
            ],
        ),
    ]
