# Generated by Django 5.2 on 2026-04-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='username',
            new_name='user',
        ),
    ]
