# Generated by Django 5.2 on 2026-05-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_appliedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
