# Generated by Django 5.2 on 2026-05-04 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='assessment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
